# Generated by Django 3.0 on 2019-12-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20191204_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='telephone',
            field=models.CharField(default=11973500236, max_length=11),
            preserve_default=False,
        ),
    ]
