# Generated by Django 3.0 on 2019-12-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_service_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(default='sdadas'),
            preserve_default=False,
        ),
    ]
